{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "model_type", "default": "random_forest", "conditions": [], "values": ["random_forest", "ridge"], "ordered": false}}, {"class_name": "Int", "config": {"name": "n_estimators", "default": null, "conditions": [], "min_value": 10, "max_value": 50, "step": 10, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "max_depth", "default": null, "conditions": [], "min_value": 3, "max_value": 10, "step": 1, "sampling": "linear"}}], "values": {"model_type": "random_forest", "n_estimators": 40, "max_depth": 7}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\laptop\\Anaconda3\\envs\\TMLC_NLP\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\laptop\\Anaconda3\\envs\\TMLC_NLP\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\laptop\\Anaconda3\\envs\\TMLC_NLP\\lib\\site-packages\\keras_tuner\\tuners\\sklearn_tuner.py\", line 168, in run_trial\n    y_train = split_data(y, train_indices)\n  File \"c:\\Users\\laptop\\Anaconda3\\envs\\TMLC_NLP\\lib\\site-packages\\keras_tuner\\tuners\\sklearn_tuner.py\", line 45, in split_data\n    raise TypeError(\nTypeError: Expected the data to be numpy.ndarray or pandas.DataFrame. Received: 0        0.0\n1        1.0\n2        0.0\n3        1.0\n4        0.0\n        ... \n10756    1.0\n10757    0.0\n10758    0.0\n10759    1.0\n10760    0.0\nName: oh_label, Length: 10761, dtype: float64.\n"}